import re

with open('index.html', 'r') as f:
    content = f.read()

# JS for code generation
code_gen_js = """
  // ===== CODE EXPORT =====
  function generateCSSCode() {
    let css = `/* Generated by Transition Studio Pro */\\n\\n`;
    css += `.scene {\\n  position: relative;\\n  width: ${state.canvasSize.w}px;\\n  height: ${state.canvasSize.h}px;\\n  background: ${state.scene.bgType === 'solid' ? state.scene.bgColor0 : `linear-gradient(${state.scene.bgAngle}deg, ${state.scene.bgColor0}, ${state.scene.bgColor1})`};\\n  overflow: hidden;\\n}\\n\\n`;

    state.elements.forEach(el => {
      let extStyle = '';
      if (el.props.effect === 'glassmorphism') {
        extStyle += `  background: rgba(255, 255, 255, 0.05);\\n  backdrop-filter: blur(20px) saturate(150%);\\n  border: 1px solid rgba(255, 255, 255, 0.1);\\n`;
      }

      css += `.el-${el.id} {\\n`;
      css += `  position: absolute;\\n  left: ${el.props.x}px;\\n  top: ${el.props.y}px;\\n  width: ${el.props.width}px;\\n  height: ${el.props.height}px;\\n`;
      if (el.props.borderRadius) css += `  border-radius: ${el.props.borderRadius}px;\\n`;
      css += extStyle;
      css += `  animation: anim-${el.id} ${el.animation.duration}ms cubic-bezier(0.4, 0, 0.2, 1) ${el.animation.delay}ms both;\\n}\\n\\n`;

      // Basic keyframe representation
      css += `@keyframes anim-${el.id} {\\n`;
      if (el.animation.type === 'fade-in') {
        css += `  0% { opacity: 0; }\\n  100% { opacity: ${el.props.opacity !== undefined ? el.props.opacity : 1}; }\\n`;
      } else if (el.animation.type.includes('scale')) {
        css += `  0% { opacity: 0; transform: scale(0.5); }\\n  100% { opacity: ${el.props.opacity !== undefined ? el.props.opacity : 1}; transform: scale(1); }\\n`;
      } else {
        css += `  0% { opacity: 0; transform: translateY(20px); }\\n  100% { opacity: ${el.props.opacity !== undefined ? el.props.opacity : 1}; transform: translateY(0); }\\n`;
      }
      css += `}\\n\\n`;
    });
    return css;
  }

  function generateReactCode() {
    let jsx = `import React from 'react';\\nimport { motion } from 'framer-motion';\\n\\nexport default function TransitionScene() {\\n  return (\\n`;
    jsx += `    <div style={{ position: 'relative', width: ${state.canvasSize.w}, height: ${state.canvasSize.h}, background: '${state.scene.bgColor0}', overflow: 'hidden' }}>\\n`;

    state.elements.forEach(el => {
      let initTransform = { opacity: 0, y: 20 };
      if (el.animation.type === 'fade-in') initTransform = { opacity: 0 };
      if (el.animation.type.includes('scale')) initTransform = { opacity: 0, scale: 0.5 };

      let endTransform = { opacity: el.props.opacity !== undefined ? el.props.opacity : 1, x: 0, y: 0, scale: 1, rotate: el.props.rotation || 0 };

      jsx += `      <motion.div\\n`;
      jsx += `        initial={${JSON.stringify(initTransform)}}\\n`;
      jsx += `        animate={${JSON.stringify(endTransform)}}\\n`;
      jsx += `        transition={{ duration: ${el.animation.duration/1000}, delay: ${el.animation.delay/1000}, ease: "easeOut" }}\\n`;
      jsx += `        style={{ position: 'absolute', left: ${el.props.x}, top: ${el.props.y}, width: ${el.props.width}, height: ${el.props.height} }}\\n`;
      jsx += `      >\\n`;
      jsx += `        {/* ${el.name} content */}\\n`;
      jsx += `      </motion.div>\\n`;
    });

    jsx += `    </div>\\n  );\\n}\\n`;
    return jsx;
  }

  function setupCodeExport() {
    document.getElementById('exportCodeBtn').addEventListener('click', () => {
      document.getElementById('codeExportModal').classList.add('active');
      document.getElementById('codeExportArea').value = generateCSSCode();
    });
    document.getElementById('closeCodeExport').addEventListener('click', () => {
      document.getElementById('codeExportModal').classList.remove('active');
    });
    document.getElementById('btnExportCSS').addEventListener('click', (e) => {
      document.getElementById('btnExportReact').classList.remove('active');
      e.target.classList.add('active');
      document.getElementById('codeExportArea').value = generateCSSCode();
    });
    document.getElementById('btnExportReact').addEventListener('click', (e) => {
      document.getElementById('btnExportCSS').classList.remove('active');
      e.target.classList.add('active');
      document.getElementById('codeExportArea').value = generateReactCode();
    });
    document.getElementById('copyCodeBtn').addEventListener('click', () => {
      navigator.clipboard.writeText(document.getElementById('codeExportArea').value);
      showToast('Code copied to clipboard!');
    });
  }
"""

content = content.replace("// ===== EXPORT =====\n", "// ===== EXPORT =====\n" + code_gen_js)

# Also need to call setupCodeExport inside init
content = content.replace("    setupCanvasDrop();", "    setupCanvasDrop();\n    setupCodeExport();")

with open('index.html', 'w') as f:
    f.write(content)
